{application, lapd_data,
	[{description,  "LAPD data passing example application"},
		{id,           "Netaccess LAPD example"},
		{vsn,          "0.1"},
		{modules,      [lapd_app, lapd_sup, lapd_fsm]},
		{registered,   []},
%		{included_applications, [netaccess]},
		{applications, [kernel, stdlib]},
		{env,
			[{server_name, pri0},
			{device_name, "/dev/pri0"},
			{board_number, 0},
			{interval, 5000},
			{lapdids, [0,1,2,3,4,5,6,7,8]}]},
		{mod,          {lapd_app, []}}]}.
